[package]
name = "rfsoc"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
pynq = {version = "0.1", path = "../pynq"}
serde = { version = "1.0.218", features = ["derive"]}
serde_json = "1.0.139"